---
language: python
dist: xenial
python:
  - 2.7
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule test
notifications:
  email: false
  slack:
    secure: R9elTmV9vLLfPYe1dcsVIbAnV/zAnvFyTgHdKBG3teddUltF3sKTERDNcPvp0PtMNVadnoZSD1Qfmkf35sdKWpriDu2ooyE6+3J+7zZwj6BfJLWzv1xaQxZu8bO9te01/izzihyD1x15LVBFDgwPPUUyTvEEtC0RWhYgQojInwz1SayQ2jLdy2OUXxg03gEe2EiOVXwQcyHOBg1c9Dm4mbzGk0fr11EQ/mmA77ULQyM9xeGG5uQJPJX5anF/v97ueNQV1a4VQtF9REqOXyFDbEqttNaVfPlbAKbKASp+72n01r1CYeavDvMyaFI0CF7xINrUYJmBRY8tYk7KVSZXIzNWuxgPXpfTe2pi/mlYbYri7sHvVo9PXkoRF1go/qytXy+I+Y/d6FCNI8FCQrHczyFHZLf1yMbHaTAVPLQfRw0FF91ijK52lzhLGZsXhrFQkY2B5ZejMa0Sh3aIsIcb4Jw7KlYk5o6LVY4tbyB3b7kyGHuwHGnI1x+5VAcM7lY8Rn+OJDQShxURKDA2cBNk+Cz3DZV6A4TDqbVBEIyVzGpFpfy6hlBNPwNbNiX3Mwmx1HmdmPYNE+na7SL2W7LIfPxFOiicS08jeRThLSnN7PTKPmImHFiriuSJpHOtkuiRntmnfc9pXYVrSzzJAEieOoaVOfXmMbHrHP6It6fRwfg=
